<a href="https://colab.research.google.com/github/MLgeek96/Interview-Preparation-Kit/blob/master/Udemy/Python%20%26%20ML%20for%20Financial%20Analysis/7_Python_101_Python_Libraries_for_Data_Analysis_Numpy_Skeleton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NUMPY BASICS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np 

# Let's define a one-dimensional array 
my_list = [10, 20, 50, 60, 70]
my_list

[10, 20, 50, 60, 70]

In [2]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [3]:
type(x)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
matrix = np.array([[5, 8], [9, 13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

In [5]:
type(matrix)

numpy.ndarray

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [6]:
matrix = np.array([[4, 6, 8, 7], [20, 5, 6, 9]])
matrix

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [7]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(15)
x

array([0.50331264, 0.87107778, 0.45180741, 0.27813039, 0.18699851,
       0.76884239, 0.28568721, 0.76429075, 0.07539206, 0.59996358,
       0.5702233 , 0.06720812, 0.93038251, 0.14345789, 0.38337854])

In [8]:
# you can create a matrix of random number as well
x = np.random.rand(5, 5)
x

array([[0.74907287, 0.35215148, 0.29908868, 0.05789703, 0.25037045],
       [0.58725576, 0.46358667, 0.29846686, 0.2602505 , 0.81400481],
       [0.1576979 , 0.42708321, 0.33748786, 0.54711254, 0.51339676],
       [0.83363231, 0.92614368, 0.64667892, 0.28248413, 0.72275485],
       [0.5338894 , 0.85696794, 0.36661266, 0.72494047, 0.61663003]])

In [9]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x

array([ 0.54663654, -0.28306667,  0.47024075, -1.0535757 ,  1.45561189,
       -1.99769526,  0.18282188, -0.38255527, -0.006062  , -1.01735649])

In [10]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10)
x

5

In [11]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([98, 11, 88, 90, 14, 47, 25, 61, 34, 29, 90, 28, 44, 86, 57])

In [12]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
# Create an evenly spaced values with a step of 5
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [14]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [15]:
# Array of ones
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
# Matrices of ones
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [17]:
# Array of zeros
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [18]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(0, x, 20)
x

Please enter a positive integer value: 39


array([ 2, 29,  8, 34, 15, 18, 21,  4, 37, 17,  5, 37,  4, 19, 36, 22, 11,
        4,  0,  2])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [19]:
# Let's define a one-dimensional array 
my_list = [-30, 4, 50, 60, 29, 15, 22, 90]
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [20]:
# Get Length of a numpy array
len(x)

8

In [21]:
# Get shape
x.shape

(8,)

In [22]:
# Obtain the datatype
x.dtype

dtype('int64')

In [23]:
# Reshape 1D array into a matrix
z = x.reshape(2, 4)
z

array([[-30,   4,  50,  60],
       [ 29,  15,  22,  90]])

In [24]:
# Obtain the maximum element (value)
x.max()

90

In [25]:
# Obtain the minimum element (value)
x.min()

-30

In [26]:
# Obtain the location of the max element
x.argmax()

7

In [27]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [28]:
x = np.arange(300, 500, 10)
x = x.reshape(4, 5)
x

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [29]:
x = np.random.randint(-1000, 1000, (20, 20))

In [30]:
x.max()

996

In [31]:
x.min()

-977

In [32]:
x.mean()

-37.1775

In [33]:
print("The maximum value is {} and the minimum value is {}".format(x.max(), x.min()))

The maximum value is 996 and the minimum value is -977


# 4. MATHEMATICAL OPERATIONS

In [34]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [38]:
sqrt = np.sqrt(x)
sqrt

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [39]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [40]:
x = np.array([3, 20, 30])
y = np.array([4, 6, 7])

z = np.sqrt(x ** 2 + y ** 2)
z

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING 

In [41]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [42]:
# Access specific index from the numpy array
x[3]

21

In [43]:
# Starting from the first index 0 up until and NOT including the last element
x[:-1]

array([20, 40, 50, 21])

In [44]:
# Broadcasting, altering several values in a numpy array at once
x[0:2] = 10
x

array([10, 10, 50, 21, 15])

In [45]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[4, 4, 2, 8, 6],
       [3, 6, 1, 8, 8],
       [6, 8, 7, 9, 3],
       [1, 2, 7, 9, 9],
       [9, 2, 1, 9, 9]])

In [46]:
# Get a row from a matrix
matrix[3]

array([1, 2, 7, 9, 9])

In [47]:
# Get one element
matrix[2][2]

7

In [48]:
mini_matrix = matrix[:3]
mini_matrix

array([[4, 4, 2, 8, 6],
       [3, 6, 1, 8, 8],
       [6, 8, 7, 9, 3]])

In [49]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[2, 8, 6],
       [1, 8, 8],
       [7, 9, 3],
       [7, 9, 9],
       [1, 9, 9]])

In [50]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[4, 4],
       [3, 6],
       [6, 8],
       [1, 2],
       [9, 2]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [51]:
x = np.array([[2, 30, 20, -2, -4], 
              [3, 4, 40, -3, -2], 
              [-3, 4, -6, 90, 10],
              [25, 45, 34, 22, 12], 
              [13, 24, 22, 32, 37]])
x[-1] = -1
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

In [52]:
mini_matrix = x[:2, -2:]
mini_matrix * 2

array([[-4, -8],
       [-6, -4]])

# 6. ELEMENTS SELECTION (CONDITIONAL)

In [53]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[6, 5, 5, 4, 7],
       [6, 2, 7, 2, 8],
       [4, 6, 6, 1, 5],
       [3, 4, 9, 2, 8],
       [6, 8, 4, 4, 4]])

In [54]:
new_matrix = matrix[matrix > 3]
new_matrix

array([6, 5, 5, 4, 7, 6, 7, 8, 4, 6, 6, 5, 4, 9, 8, 6, 8, 4, 4, 4])

In [55]:
new_matrix = matrix[matrix % 2 == 0]
new_matrix

array([6, 4, 6, 2, 2, 8, 4, 6, 6, 4, 2, 8, 6, 8, 4, 4, 4])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [56]:
matrix = np.array([[2, 30, 20, -2, -4], 
                   [3, 4, 40, -3, -2], 
                   [-3, 4, -6, 90, 10],
                   [25, 45, 34, 22, 12], 
                   [13, 24, 22, 32, 37]])
matrix[matrix < 0] = 0
matrix[matrix % 2 == 1] = 25
matrix

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [57]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

array([[[ 4,  6,  8,  7],
        [20,  5,  6,  9]]])

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [58]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

Please enter a positive integer value: 50


array([31, 43, 45, 47,  4, 18, 47, 24, 30, 41, 32,  6, 31,  1, 35, 35, 10,
       20, 15, 24])

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [59]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [60]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [61]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[  62 -273 -425  140 -111  780  732 -559 -731 -473  104  311  293  776
   231  988 -950 -495 -523  897]
 [ -89  742  601  -88 -608 -818   78 -155 -277 -864  284 -936   44 -786
   -21  491 -245  407   96 -603]
 [-715 -739  880 -413  904 -365 -951  983  289 -291  274 -594  928  817
   260  617  690  142 -256 -841]
 [ 492  295  282   79  486  755  698 -269 -241 -940 -729   70  548  726
   884  564 -817  725  673  375]
 [ 474 -559 -471 -814 -777 -916  251  659 -405   94 -897   67  851 -758
   692  811 -476 -476 -921 -615]
 [ 422 -181 -544  -43  930 -765  659  981 -570 -408 -568 -981 -543 -613
  -514  996 -526 -487  294  217]
 [-542 -699  -27 -438 -124  232 -180  488  447 -738 -903  940 -742 -978
  -141   49 -605  813 -460 -550]
 [ 845 -971  879  235  -33 -355 -527  298  476 -483 -423 -617 -664  291
   748  933   13 -157 -193 -259]
 [-496  421 -120  730 -770  291  148 -358 -384 -472 -532  798 -911  820
  -869  168  415  598 -632 -292]
 [-183 -552 -322  375 -937   49  908 -719  -40 -741  80

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [62]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [63]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [64]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [65]:
X[:2, 3:]  = X[:2, 3:] * 2

In [66]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [67]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])